version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: sigmax-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sigmax}
      POSTGRES_USER: ${POSTGRES_USER:-sigmax}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sigmax-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: sigmax-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sigmax-network

  # NATS Message Queue
  nats:
    image: nats:2-alpine
    container_name: sigmax-nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js"]
    networks:
      - sigmax-network

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: sigmax-prometheus
    restart: unless-stopped
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - sigmax-network

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: sigmax-grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_INSTALL_PLUGINS: grafana-clock-panel
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - sigmax-network
    depends_on:
      - prometheus

  # SIGMAX API
  sigmax-api:
    build:
      context: ./ui/api
      dockerfile: Dockerfile
    container_name: sigmax-api
    restart: unless-stopped
    environment:
      - POSTGRES_URL=${POSTGRES_URL:-postgresql://sigmax:changeme@postgres:5432/sigmax}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - NATS_URL=${NATS_URL:-nats://nats:4222}
    ports:
      - "8000:8000"
    networks:
      - sigmax-network
    depends_on:
      - postgres
      - redis
      - nats
    volumes:
      - ./ui/api:/app
      - ./core:/app/core

  # SIGMAX Web UI
  sigmax-ui:
    build:
      context: ./ui/web
      dockerfile: Dockerfile
    container_name: sigmax-ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - sigmax-network
    depends_on:
      - sigmax-api
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  sigmax-network:
    driver: bridge
