name: Feature Request
description: Suggest a new feature or enhancement for SIGMAX
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have reviewed the [roadmap](https://github.com/I-Onlabs/SIGMAX#-roadmap) and this feature is not already planned
          required: true
        - label: This feature aligns with SIGMAX's goals (autonomous trading, multi-agent AI, safety-first)
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Trading Strategy
        - Agent Enhancement
        - UI/UX Improvement
        - Security Enhancement
        - Performance Optimization
        - Integration (Exchange, Chain, Protocol)
        - Monitoring/Observability
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my usage)
        - High (Significantly improves experience)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Example: Currently, SIGMAX cannot detect flash loan attacks, which poses a risk when trading on DEXs.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Add a FlashLoanDetector agent that:
        1. Monitors mempool for large borrows
        2. Checks for suspicious transaction patterns
        3. Pauses trading if flash loan detected
        4. Alerts via Telegram
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: |
        - Using Flashbots RPC for transaction privacy
        - Only trading on centralized exchanges
        - Setting stricter slippage limits
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits would this feature provide?
      placeholder: |
        - Reduces risk of sandwich attacks
        - Improves trade execution quality
        - Increases user confidence in DEX trading
        - Could prevent 10-20% slippage on volatile trades
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: Technical implementation ideas (optional)
      placeholder: |
        Potential approach:
        - Use web3.py to monitor pending transactions
        - Integrate with Flashbots API for bundle detection
        - Add configuration in arbitrage_config.yaml
        - Estimated effort: 2-3 days
      render: markdown
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Screenshots, diagrams, or code examples (optional)
      placeholder: |
        Attach images or paste code examples here
    validations:
      required: false

  - type: dropdown
    id: willing_to_implement
    attributes:
      label: Willing to Implement
      description: Are you willing to implement this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, but need guidance"
        - "No, but I can help test"
        - "No"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about the feature request
      placeholder: |
        - Similar features in other projects: UniswapX, CowSwap
        - Related academic papers: [link]
        - Community discussion: [Discord thread]
    validations:
      required: false

  - type: dropdown
    id: breaking_change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes?
      options:
        - "No"
        - "Yes"
        - "Unsure"
    validations:
      required: false
