name: Security Vulnerability (Private Report)
description: Report a security vulnerability (will be treated as private)
title: "[SECURITY]: "
labels: ["security", "critical"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT: DO NOT include exploit details in public issues!**

        Please report security vulnerabilities privately to:
        **security@sigmax.dev**

        This template is for tracking acknowledged security issues.
        If you are reporting a new vulnerability, please email us directly.

        See our [Security Policy](https://github.com/I-Onlabs/SIGMAX/blob/main/SECURITY.md) for more information.

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Security Acknowledgment
      options:
        - label: I have reported this vulnerability privately to security@sigmax.dev
          required: true
        - label: I have NOT included exploit details in this public issue
          required: true
        - label: I am creating this issue only for tracking purposes after private disclosure
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity (CVSS)
      description: Estimated severity level
      options:
        - Critical (9.0-10.0) - Immediate action required
        - High (7.0-8.9) - Fix urgently
        - Medium (4.0-6.9) - Fix in next release
        - Low (0.1-3.9) - Fix when convenient
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Vulnerability Category
      description: Type of security issue
      options:
        - Authentication/Authorization
        - Injection (SQL, Command, etc.)
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Insecure Deserialization
        - API Key Exposure
        - Credential Leakage
        - Cryptographic Weakness
        - Denial of Service (DoS)
        - Trading Logic Exploit
        - Smart Contract Vulnerability
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Vulnerability Summary
      description: High-level description (NO exploit details)
      placeholder: |
        Example: "API endpoint vulnerable to authentication bypass under certain conditions"
    validations:
      required: true

  - type: textarea
    id: affected_versions
    attributes:
      label: Affected Versions
      description: Which versions are affected?
      placeholder: |
        - SIGMAX 1.0.0 - 1.2.5
        - Patched in: 1.2.6
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What are the potential consequences?
      placeholder: |
        - Unauthorized access to trading data
        - Potential for account takeover
        - Estimated risk: Medium (requires specific conditions)
    validations:
      required: true

  - type: dropdown
    id: disclosure_status
    attributes:
      label: Disclosure Status
      description: Current status of vulnerability disclosure
      options:
        - Privately Reported (awaiting response)
        - Under Investigation
        - Fix in Progress
        - Fix Released
        - Public Disclosure Approved
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Temporary Mitigation
      description: Are there any workarounds users can implement?
      placeholder: |
        Until a fix is released, users should:
        - Disable feature X
        - Use alternative method Y
        - Monitor logs for suspicious activity
    validations:
      required: false

  - type: input
    id: cve
    attributes:
      label: CVE ID (if assigned)
      description: CVE identifier if one has been assigned
      placeholder: CVE-2025-XXXXX
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Related links, advisories, or documentation
      placeholder: |
        - CWE-79: Cross-site Scripting
        - OWASP Top 10 2021: A03
        - Related issue: #123
    validations:
      required: false

  - type: dropdown
    id: bounty
    attributes:
      label: Bug Bounty
      description: Is this eligible for a bug bounty?
      options:
        - "Yes - bounty claimed"
        - "Yes - awaiting bounty"
        - "No - reporting for community benefit"
        - "Unknown"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Thank you for helping keep SIGMAX secure!**

        Your responsible disclosure helps protect all SIGMAX users.
        We will review and respond to your report as quickly as possible.
